[[redirects]]
from = "/proxy/*"
to = "https://wiztrip.o-r.kr/:splat"
status = 200
force = true

[[redirects]]
from = "/plan/:tripId/*"
to = "index.html"
status = 200

[[redirects]]
from = "/*"
to = "index.html"
status = 200